# Generated by Django 5.2.1 on 2025-05-15 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('inside', 'Inside'), ('outside', 'Outside')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('coord_x', models.FloatField()),
                ('coord_y', models.FloatField()),
                ('visits', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.place')),
            ],
        ),
    ]
