# Generated by Django 5.2.1 on 2025-05-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_place_placeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
