# Generated by Django 5.2.1 on 2025-05-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_place_xp_reward_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
