# Generated by Django 5.2.1 on 2025-05-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_savedplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='coord_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='coord_y',
            field=models.FloatField(default=0),
        ),
    ]
