# Generated by Django 5.2.1 on 2025-05-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_customuser_coord_x_customuser_coord_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='online',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
