# Generated by Django 5.2.1 on 2025-05-20 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_customuser_badges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='tags',
        ),
        migrations.DeleteModel(
            name='PlaceImage',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
